"use strict";
function toggleMenu() {
    var menu = document.getElementById("menu");
    var menuOff = document.getElementById("menu-off");
    if (menu && menuOff && menu.style.display === "block") {
        menu.style.display = "none";
        menuOff.style.display = "none";
    }
    else if (menu && menuOff) {
        menu.style.display = "block";
        menuOff.style.display = "block";
    }
}
function redirect(language) {
    if (availability[primaryKey[language]]) {
        return primary[language];
    }
    else if (alternate[language]) {
        return alternate[language];
    }
    else {
        return primary["english"];
    }
}
var availability = {
    "glow": false,
    "hope": false,
    "amazing": false,
    "egw": false,
    "youtube": true,
};
var primaryKey = {
    "english": "glow",
    "spanish": "glow",
    "portuguese": "amazing",
    "french": "amazing",
    "german": "hope",
    "russian": "amazing",
    "romanian": "glow",
    "ukrainian": "hope",
    "tagalog": "glow",
    "cebuano": "hope",
    "hindi": "hope",
    "arabic": "amazing",
    "nederlands": "glow",
    "czech": "glow",
    "hungarian": "glow",
    "indonesian": "hope",
    "amharic": "glow",
    "slovenia": "glow",
    "armenian": "glow",
    "norwegian": "glow",
    "polski": "glow",
    "italian": "hope",
    "slovak": "glow",
    "visayan": "glow",
    "japanese": "hope",
    "chinese": "glow",
    "korean": "hope",
    "swedish": "amazing",
    "icelandic": "hope",
    "finnish": "hope",
    "bulgarian": "hope",
    "bengali": "youtube",
    "bhojpuri": "youtube",
    "dayak": "youtube",
    "estonian": "youtube",
    "javanese": "youtube",
    "kannada": "youtube",
    "malagasy": "youtube",
    "malayalam": "youtube",
    "marathi": "youtube",
    "meitei": "youtube",
    "mizo": "youtube",
    "mongolian": "youtube",
    "nepali": "youtube",
    "punjabi": "youtube",
    "santali": "youtube",
    "tamil": "youtube",
    "telugu": "youtube",
    "abkhazian": "egw",
    "afrikaans": "egw",
    "akawaio": "egw",
    "albanian": "egw",
    "altay": "egw",
    "assamese": "egw",
    "avar": "egw",
    "Azerbaijani": "egw",
};
var primary = {
    "english": "https://www.glowonline.org/digital/english",
    "spanish": "https://www.glowonline.org/digital/espanol",
    "portuguese": "https://www.amazingfacts.org/pt/inicio",
    "french": "https://www.amazingfacts.org/fr/accueil",
    "german": "https://hopetv.de",
    "russian": "https://www.amazingfacts.org/ru/%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%b0%d1%8f",
    "romanian": "https://www.glowonline.org/glow-roman",
    "ukrainian": "https://tv.hope.ua",
    "tagalog": "https://www.glowonline.org/gyd/tagalog",
    "cebuano": "https://hopetv.ph/",
    "hindi": "https://hopechannelhindi.in",
    "arabic": "https://www.amazingfacts.org/ar/%d8%b9%d9%85%d9%84-%d8%a7%d9%84%d8%b1%d8%a7%d8%a6%d9%84",
    "nederlands": "https://www.glowonline.org/glow-dutch",
    "czech": "https://www.glowonline.org/czech",
    "hungarian": "https://www.glowonline.org/hungary",
    "indonesian": "https://hopechannel.id",
    "amharic": "https://www.glowonline.org/digital/amharic",
    "slovenia": "https://www.glowonline.org/glow-slovensk",
    "armenian": "https://www.glowonline.org/glow-armenian",
    "norwegian": "https://www.glowonline.org/norwegian/",
    "polski": "https://www.glowonline.org/pl",
    "italian": "https://hopemedia.it",
    "slovak": "https://www.glowonline.org/glow-slovak",
    "visayan": "https://www.glowonline.org/glow-visayan",
    "japanese": "https://www.hopechannel.jp",
    "chinese": "https://www.glowonline.org/glow-chinese",
    "korean": "https://hopechannel.kr",
    "swedish": "https://www.amazingfacts.org/sv/hem",
    "icelandic": "https://hopechannel.is",
    "finnish": "https://hopechannel.fi",
    "bulgarian": "https://hopetv.bg",
    "bengali": "https://www.youtube.com/playlist?list=PLvVAlSkq3MXT2bEO9AhxMC2zLl-YWVKc2",
    "bhojpuri": "https://www.youtube.com/playlist?list=PL089YS6WSH25sDH7ER5BgnwS7v7Bg4pCz",
    "dayak": "https://www.youtube.com/playlist?list=PLyKtCIFEspXopT_8PB3Z94nLEb8K2i-Y_&index=3",
    "estonian": "https://www.youtube.com/playlist?list=PLZEr7IMVNuJ-E-RH-shSlCrp2snoBpsHH",
    "javanese": "https://www.youtube.com/playlist?list=PL8sdRUaIOJDif3RKihBrX8AyGVwLGB4Lo",
    "kannada": "https://www.youtube.com/playlist?list=PLgNnLiuGItn9dhgqGspjuaBe8xOgbT6EA",
    "malagasy": "https://www.youtube.com/playlist?list=PLg8tlFOeVN58vwyt7-up5LZDRpdwHcbIa",
    "malayalam": "https://www.youtube.com/playlist?list=PLvsmbgvwm_ED2XeWPzCTI-kV4NyaPCTIh",
    "marathi": "https://www.youtube.com/playlist?list=PLL4YnkccIwPTGCeaN1rDoowg1t-V7yv3n",
    "meitei": "https://www.youtube.com/channel/UCb7lE7RBSzbUB_79OYDISSw",
    "mizo": "https://www.youtube.com/playlist?list=PLvaZsdR4oRfNV8NzEFVMgksOdrfjHR6Wu",
    "mongolian": "https://www.youtube.com/playlist?list=PLpa-sOKy3XOg5HlQE78epu5TySblHRr0A",
    "nepali": "https://www.youtube.com/playlist?list=PLlwfrqmdZg6duWW3JNHAh7JzEKXvkSX-7",
    "punjabi": "https://www.youtube.com/playlist?list=PL0msRlgSUO5kNPD-1ldKOzrmBJjs313pR",
    "santali": "https://www.youtube.com/playlist?list=PLancRlPt_m7dU7XssCvv6N6FtYWnCMgAY",
    "tamil": "https://www.youtube.com/playlist?list=PLT_TN2KLM48FtF3rsMUM17sLu4Q-eVu7F",
    "telugu": "https://www.youtube.com/playlist?list=PL4yGTeBkSwpQFKxOYsw0Vx7PzS53Yv6FH",
    "abkhazian": "https://egwwritings.org/read?panels=p13987.2&index=0",
    "afrikaans": "https://egwwritings.org/read?panels=p11589.2&index=0",
    "akawaio": "https://egwwritings.org/read?panels=p12275.2&index=0",
    "albanian": "https://egwwritings.org/read?panels=p14649.2&index=0",
    "altay": "https://egwwritings.org/read?panels=p12111.2&index=0",
    "assamese": "https://egwwritings.org/read?panels=p14104.3&index=0",
    "avar": "https://egwwritings.org/read?panels=p13992.2&index=0",
    "Azerbaijani": "https://egwwritings.org/read?panels=p13958.2&index=0",
};
var alternate = {
    "english": "https://hopetv.org",
    "spanish": "https://www.amazingfacts.org/es/inicio/",
    "portuguese": "https://www.novotempo.com/",
    "french": "https://hcf.tv",
    "german": "https://www.amazingfacts.org/de/startseite",
    "russian": "https://hopetv.ru/",
    "romanian": "https://www.sperantatv.ro/",
    "ukrainian": "https://www.glowonline.org/gyd/ukrainian",
    "tagalog": "https://hopetv.ph/",
    "cebuano": "https://www.youtube.com/playlist?list=PL3G8y_le8ywcmP5itbBKMjfnONkaffZag",
    "hindi": "https://www.youtube.com/playlist?list=PLOky4rbGNIg5dHBNuJvvqgMa2Ii6KpnIe",
    "arabic": "https://www.youtube.com/playlist?list=PLWT5oIAjLwXM4WJsRmeK98F4x7P5MupWk",
    "nederlands": "https://hopechannel.dk",
    "czech": "http://www.hopetv.cz",
    "hungarian": "https://remenytv.hu",
    "indonesian": "https://www.glowonline.org/glow-indonesian",
    "amharic": "https://egwwritings.org/read?panels=p14077.2&index=0",
    "slovenia": "",
    "armenian": "https://egwwritings.org/read?panels=p11414.89&index=0",
    "norwegian": "https://hopechannel.no",
    "polski": "https://hopechannel.pl",
    "italian": "https://www.amazingfacts.org/it/casa",
    "slovak": "",
    "visayan": "https://hopetv.ph",
    "japanese": "https://www.amazingfacts.org/ja/%e3%83%9b%e3%83%bc%e3%83%a0",
    "chinese": "https://www.chinesehope.tv",
    "korean": "https://www.amazingfacts.org/ko/%ed%99%88",
    "swedish": "",
    "icelandic": "",
    "finnish": "",
    "bulgarian": "",
    "bengali": "",
    "bhojpuri": "",
    "dayak": "",
    "estonian": "",
    "javanese": "",
    "kannada": "",
    "malagasy": "",
    "malayalam": "",
    "marathi": "",
    "meitei": "",
    "mizo": "",
    "mongolian": "",
    "nepali": "",
    "punjabi": "",
    "santali": "",
    "tamil": "",
    "telugu": "",
};
//# sourceMappingURL=functions.js.map